name = "learnforge-proxy"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "learnforge-db"
database_id = "8d46fcd8-d679-4f07-8edd-a425a9f7dc87"
